name: sync-template

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: olafkotur/obsidian-plugin-template
          upstream_branch: main
